/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DocSurgeryManagement.Forms;

import DocSurgeryManagement.DataManager;
import javax.swing.JOptionPane;

/**
 *
 * @author C-bre
 */
public class CreateAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T_Name = new javax.swing.JTextField();
        T_Address = new javax.swing.JTextField();
        T_Age = new javax.swing.JTextField();
        B_CreateAccount = new javax.swing.JButton();
        B_Back = new javax.swing.JButton();
        T_Password = new javax.swing.JTextField();
        T_UserID = new javax.swing.JTextField();
        T_Sex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        T_Name.setText("Name");
        T_Name.setName("T_Name"); // NOI18N
        T_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_NameActionPerformed(evt);
            }
        });

        T_Address.setText("Address");
        T_Address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_AddressActionPerformed(evt);
            }
        });

        T_Age.setText("22");

        B_CreateAccount.setText("Create Account");
        B_CreateAccount.setToolTipText("");
        B_CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreateAccountActionPerformed(evt);
            }
        });

        B_Back.setText("Back");
        B_Back.setToolTipText("");
        B_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_BackActionPerformed(evt);
            }
        });

        T_Password.setText("Password");
        T_Password.setName("T_Name"); // NOI18N
        T_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_PasswordActionPerformed(evt);
            }
        });

        T_UserID.setText("UserID");
        T_UserID.setName("T_Name"); // NOI18N
        T_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_UserIDActionPerformed(evt);
            }
        });

        T_Sex.setText("Sex");
        T_Sex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_SexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(T_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B_Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(T_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B_CreateAccount))
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(T_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(T_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(T_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(T_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(T_Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_CreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        T_Name.getAccessibleContext().setAccessibleName("B_Name");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void T_AddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_AddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_AddressActionPerformed

    private void T_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_NameActionPerformed

    private void B_CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreateAccountActionPerformed

        String inID = T_UserID.getText();
        String inPassword = T_Password.getText();
        String inFullName = T_Name.getText();
        String inAddress = T_Address.getText();
        String inAge = T_Age.getText();
        String inSex = T_Sex.getText();
        
        if (!(inID.length() == 5 && inID.length() <= 5)) {
            JOptionPane.showMessageDialog(null, 
                "User ID should must include a letter indicating user type and 4 digits afterwards.", 
                "Register Error", 
                JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        if (!(inPassword.length() >= 4 && inPassword.length() <= 16)) {
            JOptionPane.showMessageDialog(null, 
                "Password should be between 4 and 16 characters long.", 
                "Register Error", 
                JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        if (!(inFullName.length() >= 4 && inFullName.length() <= 64)) {
            JOptionPane.showMessageDialog(null, 
                "Full name should be between 3 and 64 characters long.", 
                "Register Error", 
                JOptionPane.WARNING_MESSAGE);
         
            return;
        }
        
        if (!(inAddress.length() >= 4 && inAddress.length() <= 128)) {
            JOptionPane.showMessageDialog(null, 
                "Address should be between 4 and 128 characters long.", 
                "Register Error", 
                JOptionPane.WARNING_MESSAGE);
            
            return;
        }
        
        if (DataManager.UserFindByID(inID) != null) {
            
JOptionPane.showMessageDialog(null, "THIS IS ALREADY EXISTS.", "SOMETHING WENT WRONG", JOptionPane.INFORMATION_MESSAGE);
        
            return;
        }
        
        
        boolean IsPatientCreated = DataManager.UserRegister("PATIENT", inID, inPassword, inFullName, inAddress, inSex, Integer.parseInt(inAge));
        
        if (IsPatientCreated) {
            dispose();
            Login c = new Login();
            c.setVisible(true);
        } else {
        
            JOptionPane.showMessageDialog(null, "Message: Something has gone wrong, please contact the system administrator.", "SOMETHING WENT WRONG", JOptionPane.INFORMATION_MESSAGE);
        
        }
        //JOptionPane.showMessageDialog(null, "Message: Your account has been submitted for approval.", "MESSAGE TITLE", JOptionPane.INFORMATION_MESSAGE);

        // TODO add your handling code here:
    }//GEN-LAST:event_B_CreateAccountActionPerformed

    private void B_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_BackActionPerformed
        dispose();
        Login c = new Login();
        c.setVisible(true);
    }//GEN-LAST:event_B_BackActionPerformed

    private void T_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_PasswordActionPerformed

    private void T_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_UserIDActionPerformed

    private void T_SexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T_SexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T_SexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Back;
    private javax.swing.JButton B_CreateAccount;
    private javax.swing.JTextField T_Address;
    private javax.swing.JTextField T_Age;
    private javax.swing.JTextField T_Name;
    private javax.swing.JTextField T_Password;
    private javax.swing.JTextField T_Sex;
    private javax.swing.JTextField T_UserID;
    // End of variables declaration//GEN-END:variables
}
