/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DocSurgeryManagement.Forms;

/**
 *
 * @author C-bre
 */
public class MenuDoctor extends javax.swing.JFrame {

    /**
     * Creates new form DoctorMenu
     */
    public MenuDoctor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_ViewAppointments = new javax.swing.JButton();
        B_PatientHistory = new javax.swing.JButton();
        B_CreateAppointment = new javax.swing.JButton();
        B_PrescribeMedicine = new javax.swing.JButton();
        B_CreateMedicine = new javax.swing.JButton();
        B_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_ViewAppointments.setText("View Appointments");
        B_ViewAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ViewAppointmentsActionPerformed(evt);
            }
        });

        B_PatientHistory.setText("Patient History");
        B_PatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PatientHistoryActionPerformed(evt);
            }
        });

        B_CreateAppointment.setText("Create Appointment");
        B_CreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreateAppointmentActionPerformed(evt);
            }
        });

        B_PrescribeMedicine.setText("Prescribe Medicine");
        B_PrescribeMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PrescribeMedicineActionPerformed(evt);
            }
        });

        B_CreateMedicine.setText("Create Medicine");
        B_CreateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreateMedicineActionPerformed(evt);
            }
        });

        B_Logout.setText("Logout");
        B_Logout.setToolTipText("");
        B_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(B_CreateAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_PatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_ViewAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(B_PrescribeMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_CreateMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(B_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_ViewAppointments)
                    .addComponent(B_PrescribeMedicine))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_PatientHistory)
                    .addComponent(B_CreateMedicine))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_CreateAppointment)
                    .addComponent(B_Logout))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CreateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreateMedicineActionPerformed
        dispose();
        CreateMedicine c = new CreateMedicine();
        c.setVisible(true);
    }//GEN-LAST:event_B_CreateMedicineActionPerformed

    private void B_PatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PatientHistoryActionPerformed
        dispose();
        PatientHistory c = new PatientHistory();
        c.setVisible(true);
    }//GEN-LAST:event_B_PatientHistoryActionPerformed

    private void B_PrescribeMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PrescribeMedicineActionPerformed
        dispose();
        ViewPatients c = new ViewPatients();
        c.setVisible(true);
    }//GEN-LAST:event_B_PrescribeMedicineActionPerformed

    private void B_ViewAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ViewAppointmentsActionPerformed
        dispose();
        ViewAppointments c = new ViewAppointments();
        c.setVisible(true);
    }//GEN-LAST:event_B_ViewAppointmentsActionPerformed

    private void B_CreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreateAppointmentActionPerformed
        dispose();
        BookAppointment c = new BookAppointment();
        c.setVisible(true);
    }//GEN-LAST:event_B_CreateAppointmentActionPerformed

    private void B_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LogoutActionPerformed
        dispose();
        Login c = new Login();
        c.setVisible(true);
    }//GEN-LAST:event_B_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_CreateAppointment;
    private javax.swing.JButton B_CreateMedicine;
    private javax.swing.JButton B_Logout;
    private javax.swing.JButton B_PatientHistory;
    private javax.swing.JButton B_PrescribeMedicine;
    private javax.swing.JButton B_ViewAppointments;
    // End of variables declaration//GEN-END:variables
}
