/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DocSurgeryManagement.Forms;

/**
 *
 * @author C-bre
 */
public class MenuSecretary extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryMenu
     */
    public MenuSecretary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B_AppointmentRequest = new javax.swing.JButton();
        B_CreateAppointment = new javax.swing.JButton();
        B_MedicineStock = new javax.swing.JButton();
        B_RemovePatients = new javax.swing.JButton();
        B_AccountRequests = new javax.swing.JButton();
        B_Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B_AppointmentRequest.setText("Appointment Requests");
        B_AppointmentRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AppointmentRequestActionPerformed(evt);
            }
        });

        B_CreateAppointment.setText("Create Appointments");
        B_CreateAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreateAppointmentActionPerformed(evt);
            }
        });

        B_MedicineStock.setText("Medicine Stock");
        B_MedicineStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MedicineStockActionPerformed(evt);
            }
        });

        B_RemovePatients.setText("Remove Patients");
        B_RemovePatients.setToolTipText("");
        B_RemovePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RemovePatientsActionPerformed(evt);
            }
        });

        B_AccountRequests.setText("Account Requests");
        B_AccountRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_AccountRequestsActionPerformed(evt);
            }
        });

        B_Logout.setText("Logout");
        B_Logout.setToolTipText("");
        B_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(B_RemovePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B_AppointmentRequest)
                            .addComponent(B_AccountRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_CreateAppointment, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(B_MedicineStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_AppointmentRequest)
                    .addComponent(B_CreateAppointment))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_MedicineStock)
                    .addComponent(B_AccountRequests))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_RemovePatients)
                    .addComponent(B_Logout))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_AppointmentRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AppointmentRequestActionPerformed
        dispose();
        AppointmentRequests c = new AppointmentRequests();
        c.setVisible(true);
    }//GEN-LAST:event_B_AppointmentRequestActionPerformed

    private void B_MedicineStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MedicineStockActionPerformed
        dispose();
        MedicineStock c = new MedicineStock();
        c.setVisible(true);
    }//GEN-LAST:event_B_MedicineStockActionPerformed

    private void B_CreateAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreateAppointmentActionPerformed
        dispose();
        ViewAppointments c = new ViewAppointments();
        c.setVisible(true);
    }//GEN-LAST:event_B_CreateAppointmentActionPerformed

    private void B_AccountRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_AccountRequestsActionPerformed
        dispose();
        AccountRequests c = new AccountRequests();
        c.setVisible(true);
    }//GEN-LAST:event_B_AccountRequestsActionPerformed

    private void B_RemovePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RemovePatientsActionPerformed
        dispose();
        ViewPatients c = new ViewPatients();
        c.setVisible(true);
    }//GEN-LAST:event_B_RemovePatientsActionPerformed

    private void B_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LogoutActionPerformed
        dispose();
        Login c = new Login();
        c.setVisible(true);
    }//GEN-LAST:event_B_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSecretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSecretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSecretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSecretary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSecretary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_AccountRequests;
    private javax.swing.JButton B_AppointmentRequest;
    private javax.swing.JButton B_CreateAppointment;
    private javax.swing.JButton B_Logout;
    private javax.swing.JButton B_MedicineStock;
    private javax.swing.JButton B_RemovePatients;
    // End of variables declaration//GEN-END:variables
}
